### ISSUE TITLE
file format

### ISSUE THREAD

**Issue by AntoineRousseau97** [mr-sheg/orpl#2]
Bonjour, est-ce que vous pensez implementer bientot une option pour lire les fichiers .txt? De plus, est-ce possible d'exporter les données en .txt une fois le baseline enlevé?

Merci

**Comment by DrSheg** [comment]
The problem with supporting .txt data is the infinite number of conventions for their structure. For now, I have implemented 2 _raw text_ file formats: .sdf (spectrum data file) and .rdf (raman data file). Although the file extensions are not ".txt", they are both text files that can be read with any text editor (notepad, Textedit, ...). It's quite possible to convert an arbitrary given .txt file to a valid .sdf (see attached .sdf for reference).

The exported files from ORPL (.rdf) are also _plain text_ files and can be opened in any text editor or even spreadsheet software (see screenshot below)

I hope this is sufficient for the moment. If not, you can send me a private email, so we can figure something out ;)

![image](https://github.com/mr-sheg/orpl/assets/27356351/152c74c0-6d99-4b0a-b5ae-1d886259e6c3)

[Nylon.sdf.zip](https://github.com/mr-sheg/orpl/files/11679072/Nylon.sdf.zip)

**Comment by AntoineRousseau97** [comment]
maybe its because im on mac, but the .sif and the .wdf format are not supported with textedit. So i am forced to use the .json format, which now i managed to work with! but now, i am not able to process my data... I think that it is because my "background" array is only zeros. Maybe you can help me with that?

Here is what i see in the GUI: 

<img width="1432" alt="Screenshot 2023-06-07 at 11 52 40 AM" src="https://github.com/mr-sheg/orpl/assets/66680705/5c2b1d1c-4b05-452b-8505-6f7b3b623d08">

**Comment by DrSheg** [comment]
Yeah, .sif and .wdf are binary file formats from Andor and Renishaw. I'm afraid there is not much I can do about those (although they are compatible with ORPL, you won't be able to read them as txt). 
Based on your screenshot I imagine you clicked the "update" button and nothing happened? If that is the case, you can have a look at the Log tab, it'll give you some detail about the issue. You can also copy the log as text from the Log tab or find all log files in your home folder ~/orpl/logs/. It would help a great deal if you could attach a log file here.

**Comment by AntoineRousseau97** [comment]
i cannot attach my .json file, but here is the errors i get:

2023-06-07 14:14:04,872 - INFO(orplGUI.py:process_spectra)(orplGUI.py:567) - Processing spectra
2023-06-07 14:14:04,913 - ERROR(orplGUI.py:process_spectra)(orplGUI.py:578) - Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orpl/gui/orplGUI.py", line 573, in process_spectra
    raman, baseline, irf_correction = self.process_spectrum(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orpl/gui/orplGUI.py", line 537, in process_spectrum
    raman, baseline = bubblefill(spectrum_, min_bubble_widths=width)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orpl/baseline_removal.py", line 513, in bubblefill
    poly_fit = np.poly1d(np.polyfit(xaxis, spectrum, fit_order))(xaxis)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/lib/polynomial.py", line 1244, in __init__
    raise ValueError("Polynomial must be 1d only.")
ValueError: Polynomial must be 1d only.

2023-06-07 14:14:04,916 - ERROR(orplGUI.py:process_spectra)(orplGUI.py:578) - Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orpl/gui/orplGUI.py", line 573, in process_spectra
    raman, baseline, irf_correction = self.process_spectrum(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orpl/gui/orplGUI.py", line 537, in process_spectrum
    raman, baseline = bubblefill(spectrum_, min_bubble_widths=width)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orpl/baseline_removal.py", line 513, in bubblefill
    poly_fit = np.poly1d(np.polyfit(xaxis, spectrum, fit_order))(xaxis)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/lib/polynomial.py", line 1244, in __init__
    raise ValueError("Polynomial must be 1d only.")
ValueError: Polynomial must be 1d only.

2023-06-07 14:14:04,919 - ERROR(orplGUI.py:process_spectra)(orplGUI.py:578) - Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orpl/gui/orplGUI.py", line 573, in process_spectra
    raman, baseline, irf_correction = self.process_spectrum(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orpl/gui/orplGUI.py", line 537, in process_spectrum
    raman, baseline = bubblefill(spectrum_, min_bubble_widths=width)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orpl/baseline_removal.py", line 513, in bubblefill
    poly_fit = np.poly1d(np.polyfit(xaxis, spectrum, fit_order))(xaxis)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/lib/polynomial.py", line 1244, in __init__
    raise ValueError("Polynomial must be 1d only.")
ValueError: Polynomial must be 1d only.

2023-06-07 14:14:04,920 - INFO(orplGUI.py:plot_irf_corrections)(orplGUI.py:638) - Plotting spectra after irf corrections
2023-06-07 14:14:04,994 - INFO(orplGUI.py:plot_baseline_fit)(orplGUI.py:611) - Plotting baseline fits
2023-06-07 14:14:05,038 - INFO(orplGUI.py:plot_processed_spectra)(orplGUI.py:585) - Plotting processed spectra

**Comment by AntoineRousseau97** [comment]
when i try with your example data, i get this is the log:
2023-06-07 14:33:27,721 - INFO(orplGUI.py:process_spectra)(orplGUI.py:567) - Processing spectra
2023-06-07 14:33:27,729 - INFO(orplGUI.py:plot_irf_corrections)(orplGUI.py:638) - Plotting spectra after irf corrections
2023-06-07 14:33:27,803 - INFO(orplGUI.py:plot_baseline_fit)(orplGUI.py:611) - Plotting baseline fits
2023-06-07 14:33:27,849 - INFO(orplGUI.py:plot_processed_spectra)(orplGUI.py:585) - Plotting processed spectra


and when i try with my data, i get this in the log:
2023-06-07 14:30:51,019 - INFO(orplGUI.py:process_spectra)(orplGUI.py:567) - Processing spectra
2023-06-07 14:30:51,044 - INFO(orplGUI.py:plot_irf_corrections)(orplGUI.py:638) - Plotting spectra after irf corrections
2023-06-07 14:30:51,112 - INFO(orplGUI.py:plot_baseline_fit)(orplGUI.py:611) - Plotting baseline fits
2023-06-07 14:30:51,159 - INFO(orplGUI.py:plot_processed_spectra)(orplGUI.py:585) - Plotting processed spectra


but then i "update" the processing wth my data, i get what i see in the image i sent earlier. Maybe its because i have only 1 spectrum per .json file? in your examples, you have at least 5 spectra per file.

**Comment by AntoineRousseau97** [comment]
problem was background was an array full of 0, i changed it for ones because i dont have the background, now it works!
